name: Build Desktop App

on:
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main
    workflow_dispatch: # Allows manual triggering from GitHub Actions tab
    release:
        types: [created] # Triggers when you create a GitHub release

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run make
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload macOS build artifacts
              if: matrix.os == 'macos-latest'
              uses: actions/upload-artifact@v4
              with:
                  name: macos-build
                  path: |
                      out/make/*.dmg
                      out/make/*.zip
                  retention-days: 90

            - name: Upload Windows build artifacts
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v4
              with:
                  name: windows-build
                  path: |
                      out/make/**/*.exe
                      out/make/**/*.zip
                  retention-days: 90

            - name: Upload Linux build artifacts
              if: matrix.os == 'ubuntu-latest'
              uses: actions/upload-artifact@v4
              with:
                  name: linux-build
                  path: |
                      out/make/**/*.AppImage
                      out/make/**/*.deb
                      out/make/**/*.rpm
                  retention-days: 90

